package dao;

import model.Family;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Family
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Family
     *
     * @mbggenerated
     */
    int insert(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Family
     *
     * @mbggenerated
     */
    int insertSelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Family
     *
     * @mbggenerated
     */
    Family selectByPrimaryKey(Integer fid);

    List<Family> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Family
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Family
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Family record);
}