package model;

public class Demo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.a
     *
     * @mbggenerated
     */
    private String a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.b
     *
     * @mbggenerated
     */
    private String b;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.a
     *
     * @return the value of demo.a
     *
     * @mbggenerated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.a
     *
     * @param a the value for demo.a
     *
     * @mbggenerated
     */
    public void setA(String a) {
        this.a = a == null ? null : a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.b
     *
     * @return the value of demo.b
     *
     * @mbggenerated
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.b
     *
     * @param b the value for demo.b
     *
     * @mbggenerated
     */
    public void setB(String b) {
        this.b = b == null ? null : b.trim();
    }
}